config/routes.rb
Rails.application.routes.draw do
  get 'users/index'
  get 'users/approve_user'
  get 'users/destroy'
  devise_for :users
  resources :candidate_rounds
  resources :rounds
  resources :candidates
  resources :political_parties
  resources :parliamentary_constituencies
  resources :states
  root to: "states#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/candidate_round.rb
class CandidateRound < ApplicationRecord
end

app/controllers/candidate_rounds_controller.rb
class CandidateRoundsController < ApplicationController
  before_action :set_candidate_round, only: [:show, :edit, :update, :destroy]

  # GET /candidate_rounds
  # GET /candidate_rounds.json
  def index
    @candidate_rounds = CandidateRound.all
  end

  # GET /candidate_rounds/1
  # GET /candidate_rounds/1.json
  def show
  end

  # GET /candidate_rounds/new
  def new
    @candidate_round = CandidateRound.new
  end

  # GET /candidate_rounds/1/edit
  def edit
  end

  # POST /candidate_rounds
  # POST /candidate_rounds.json
  def create
    @candidate_round = CandidateRound.new(candidate_round_params)

    respond_to do |format|
      if @candidate_round.save
        format.html { redirect_to @candidate_round, notice: 'Candidate round was successfully created.' }
        format.json { render :show, status: :created, location: @candidate_round }
      else
        format.html { render :new }
        format.json { render json: @candidate_round.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /candidate_rounds/1
  # PATCH/PUT /candidate_rounds/1.json
  def update
    respond_to do |format|
      if @candidate_round.update(candidate_round_params)
        total_votes = candidate_round_params[:total_votes]
        round = Round.where(["id = :u", { u: candidate_round_params[:round_number] }]).first
        round.total_votes = (round.total_votes.to_i + total_votes.to_i).to_s
        round.save
        candidate = Candidate.where(["id = :u", { u: candidate_round_params[:candidate] }]).first
        candidate.total_votes = (candidate.total_votes.to_i + total_votes.to_i).to_s
        candidate.save
        # constituency = ParliamentaryConstituency.where(["id = :u", { u: candidate.constituency }]).first
        format.html { redirect_to round, notice: 'Candidate round was successfully updated.' }
        format.json { render :show, status: :ok, location: @candidate_round }
      else
        format.html { render :edit }
        format.json { render json: @candidate_round.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /candidate_rounds/1
  # DELETE /candidate_rounds/1.json
  def destroy
    @candidate_round.destroy
    respond_to do |format|
      format.html { redirect_to candidate_rounds_url, notice: 'Candidate round was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_candidate_round
      @candidate_round = CandidateRound.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def candidate_round_params
      params.require(:candidate_round).permit(:total_votes, :candidate, :round_number)
    end
end

app/helpers/candidate_rounds_helper.rb
module CandidateRoundsHelper
end

app/views/candidate_rounds/_form.html.erb
<%= form_with(model: candidate_round, local: true) do |form| %>
  <% if candidate_round.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(candidate_round.errors.count, "error") %> prohibited this candidate_round from being saved:</h2>

      <ul>
      <% candidate_round.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% round = Round.where(["id = :u", {u: @candidate_round.round_number}]).first %>
  <% candidate = Candidate.where(["id = :u", {u: @candidate_round.candidate}]).first %>

  <div class="form-group">
    <div class="field">
      <strong><label>Serial Number</label></strong>
      <label><%= candidate.serial_number %></label>
    </div>
  </div>
  <div class="form-group">
    <div class="field">
      <strong><label><%= form.label :candidate %></label></strong>
      <label><%= candidate.candidate_name %></label>
      <%= form.hidden_field :candidate, value: @candidate_round.candidate %>
    </div>
  </div>
  <div class="form-group">
    <div class="field">
      <strong><label><%= form.label :round_number %></label></strong>
      <label><%= round.round_number %></label>
      <%= form.hidden_field :round_number, value: @candidate_round.round_number %>
    </div>
  </div>
  <div class="form-group">
    <div class="field">
      <label><%= form.label :total_votes %></label>
      <%= form.number_field :total_votes, class: "form-control"  %>
    </div>
  </div>
  <div class="form-group">
    <div class="actions">
      <%= form.submit "Save Votes for Candidate", class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/candidate_rounds/edit.html.erb
<% round = Round.where(["id = :u", { u: @candidate_round.round_number }]).first %>
<%= link_to 'Back to Round', round, class: "btn btn-secondary" %>
<br>
<hr>
<br>
<h1>Editing Candidate Round</h1>

<%= render 'form', candidate_round: @candidate_round %>

app/views/candidate_rounds/index.html.erb
<h1>Candidate Rounds</h1>

<table>
  <thead>
    <tr>
      <th>Total votes</th>
      <th>Candidate</th>
      <th>Round number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @candidate_rounds.each do |candidate_round| %>
      <tr>
        <td><%= candidate_round.total_votes %></td>
        <td><%= candidate_round.candidate %></td>
        <td><%= candidate_round.round_number %></td>
        <td><%= link_to 'Show', candidate_round %></td>
        <td><%= link_to 'Edit', edit_candidate_round_path(candidate_round) %></td>
        <td><%= link_to 'Destroy', candidate_round, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Candidate Round', new_candidate_round_path %>

app/views/candidate_rounds/new.html.erb
<h1>New Candidate Round</h1>

<%= render 'form', candidate_round: @candidate_round %>

<%= link_to 'Back', candidate_rounds_path %>

app/views/candidate_rounds/show.html.erb
<p>
  <strong>Total votes:</strong>
  <%= @candidate_round.total_votes %>
</p>

<p>
  <strong>Candidate:</strong>
  <%= @candidate_round.candidate %>
</p>

<p>
  <strong>Round number:</strong>
  <%= @candidate_round.round_number %>
</p>

<%= link_to 'Edit', edit_candidate_round_path(@candidate_round) %> |
<%= link_to 'Back', candidate_rounds_path %>