config/routes.rb
Rails.application.routes.draw do
  get 'users/index'
  get 'users/approve_user'
  get 'users/destroy'
  devise_for :users
  resources :candidate_rounds
  resources :rounds
  resources :candidates
  resources :political_parties
  resources :parliamentary_constituencies
  resources :states
  root to: "states#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/parliamentary_constituency.rb
class ParliamentaryConstituency < ApplicationRecord
end

app/controllers/parliamentary_constituencies_controller.rb
class ParliamentaryConstituenciesController < ApplicationController
  before_action :set_parliamentary_constituency, only: [:show, :edit, :update, :destroy]

  # GET /parliamentary_constituencies
  # GET /parliamentary_constituencies.json
  def index
    @parliamentary_constituencies = ParliamentaryConstituency.all
  end

  # GET /parliamentary_constituencies/1
  # GET /parliamentary_constituencies/1.json
  def show
  end

  # GET /parliamentary_constituencies/new
  def new
    @parliamentary_constituency = ParliamentaryConstituency.new
  end

  # GET /parliamentary_constituencies/1/edit
  def edit
  end

  # POST /parliamentary_constituencies
  # POST /parliamentary_constituencies.json
  def create
    @parliamentary_constituency = ParliamentaryConstituency.new(parliamentary_constituency_params)

    respond_to do |format|
      if @parliamentary_constituency.save
        format.html { redirect_to @parliamentary_constituency, notice: 'Parliamentary constituency was successfully created.' }
        format.json { render :show, status: :created, location: @parliamentary_constituency }
      else
        format.html { render :new }
        format.json { render json: @parliamentary_constituency.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /parliamentary_constituencies/1
  # PATCH/PUT /parliamentary_constituencies/1.json
  def update
    respond_to do |format|
      if @parliamentary_constituency.update(parliamentary_constituency_params)
        format.html { redirect_to @parliamentary_constituency, notice: 'Parliamentary constituency was successfully updated.' }
        format.json { render :show, status: :ok, location: @parliamentary_constituency }
      else
        format.html { render :edit }
        format.json { render json: @parliamentary_constituency.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /parliamentary_constituencies/1
  # DELETE /parliamentary_constituencies/1.json
  def destroy
    @parliamentary_constituency.destroy
    respond_to do |format|
      format.html { redirect_to parliamentary_constituencies_url, notice: 'Parliamentary constituency was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_parliamentary_constituency
      @parliamentary_constituency = ParliamentaryConstituency.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def parliamentary_constituency_params
      params.require(:parliamentary_constituency).permit(:pc_code, :pc_name, :geometry_type, :geometry_coordinates)
    end
end

app/helpers/parliamentary_constituencies_helper.rb
module ParliamentaryConstituenciesHelper
end

app/views/parliamentary_constituencies/_form.html.erb
<%= form_with(model: parliamentary_constituency, local: true) do |form| %>
  <% if parliamentary_constituency.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(parliamentary_constituency.errors.count, "error") %> prohibited this parliamentary_constituency from being saved:</h2>

      <ul>
      <% parliamentary_constituency.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :pc_code %>
    <%= form.text_field :pc_code %>
  </div>

  <div class="field">
    <%= form.label :pc_name %>
    <%= form.text_field :pc_name %>
  </div>

  <div class="field">
    <%= form.label :geometry_type %>
    <%= form.text_field :geometry_type %>
  </div>

  <div class="field">
    <%= form.label :geometry_coordinates %>
    <%= form.text_area :geometry_coordinates %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/parliamentary_constituencies/edit.html.erb
<h1>Editing Parliamentary Constituency</h1>

<%= render 'form', parliamentary_constituency: @parliamentary_constituency %>

<%= link_to 'Show', @parliamentary_constituency %> |
<%= link_to 'Back', parliamentary_constituencies_path %>

app/views/parliamentary_constituencies/index.html.erb
<h1>Parliamentary Constituencies</h1>

<table>
  <thead>
    <tr>
      <th>Pc code</th>
      <th>Pc name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @parliamentary_constituencies.each do |parliamentary_constituency| %>
      <tr>
        <td><%= parliamentary_constituency.pc_code %></td>
        <td><%= parliamentary_constituency.pc_name %></td>
        <td><%= link_to 'Show', parliamentary_constituency %></td>
        <td><%= link_to 'Edit', edit_parliamentary_constituency_path(parliamentary_constituency) %></td>
        <td><%= link_to 'Destroy', parliamentary_constituency, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Parliamentary Constituency', new_parliamentary_constituency_path %>

app/views/parliamentary_constituencies/new.html.erb
<h1>New Parliamentary Constituency</h1>

<%= render 'form', parliamentary_constituency: @parliamentary_constituency %>

<%= link_to 'Back', parliamentary_constituencies_path %>

app/views/parliamentary_constituencies/show.html.erb
<% if user_signed_in? and current_user.has_role? :admin %>
  <%= link_to 'New Candidate', new_candidate_path(constituency: @parliamentary_constituency.id), class: "btn btn-primary" %>
<% end %>
<% if user_signed_in? and (current_user.has_role? :approved or current_user.has_role? :admin) %>
  <%= link_to 'New Counting Round', new_round_path(constituency: @parliamentary_constituency.id), class: "btn btn-primary" %>
<% end %>

<br>
<br>
<h2 style="text-align:center;">
  <strong><%= "#{@parliamentary_constituency.pc_code} - #{@parliamentary_constituency.pc_name}" %></strong>
</h2>
<br>
<br>
<h4>
  <strong>Candidates</strong>
</h4>

<% total_votes_constituency = 0 %>
<% rounds = Round.where(["constituency = :u", {u: @parliamentary_constituency.id}]) %>
<table class="table">
  <thead>
  <tr align="center">
    <th scope="col">Political Party</th>
    <th scope="col">Serial Number</th>
    <th scope="col">Candidate Name</th>
    <th scope="col">Photograph</th>
    <th scope="col">Total Votes</th>
    <% if user_signed_in? and current_user.has_role? :admin %>
      <th colspan="3" scope="col"></th>
    <% else %>
      <th colspan="1" scope="col"></th>
    <% end %>
  </tr>
  </thead>

  <tbody>
  <% Candidate.where(["constituency = :u", {u: @parliamentary_constituency.id}]).sort_by{ |obj| obj.serial_number }.each do |candidate| %>
    <% party = PoliticalParty.where(["id = :u", {u: candidate.political_party}]).first %>
    <tr>
      <td align="center">
        <img src=<%= party.party_symbol %> height="48" width="48"><br>
        <%= party.party_name %></td>
      <td align="center"><%= candidate.serial_number %></td>
      <td><%= candidate.candidate_name %></td>
      <td align="center"><img src=<%= candidate.photograph %> height="48" width="48"></td>
      <td align="center"><%= candidate.total_votes %></td>
      <% total_votes_constituency += candidate.total_votes.to_i %>
      <td><%= link_to 'Show', candidate, class: "btn btn-info" %></td>
      <% if user_signed_in? and current_user.has_role? :admin %>
        <td><%= link_to 'Edit', edit_candidate_path(id: candidate, constituency: @parliamentary_constituency.id), class: "btn btn-warning" %></td>
        <% if rounds.length == 0 %>
          <td><%= link_to 'Destroy', candidate, method: :delete, data: {confirm: 'Are you sure?'}, class: "btn btn-danger" %></td>
        <% end %>
      <% end %>
    </tr>
  <% end %>
  <tr>
    <td colspan="4" align="center"><strong>TOTAL</strong></td>
    <td align="center"><strong><%= total_votes_constituency %></strong></td>
    <td colspan="3"></td>
  </tr>
  </tbody>
</table>

<br>
<br>

<% if total_votes_constituency != 0 %>
  <div class="progress" style="height: 30px;">
    <% Candidate.where(["constituency = :u", {u: @parliamentary_constituency.id}]).sort_by{ |obj| obj.serial_number }.each do |candidate| %>
      <% party = PoliticalParty.where(["id = :u", {u: candidate.political_party}]).first %>
      <% party_color = "#" + party.party_color %>
      <% width = 0 %>
      <% if (candidate.total_votes != 0) %>
        <% width = candidate.total_votes.to_f * 100 / total_votes_constituency.to_f %>
      <% end %>
      <div class="progress-bar" style="height: 30px; width:<%= width %>%; background-color: <%= party_color %>;">
        <%= "#{party.party_code} (#{width.round(2)}%)" %>
      </div>
    <% end %>
  </div>
<% end %>
<br>
<br>
<h4>
  <strong>Counting Rounds</strong>
</h4>
<% total_votes_constituency %>
<table class="table">
  <thead>
  <tr align="center">
    <th scope="col">Serial Number</th>
    <th scope="col">Political party</th>
    <th scope="col">Candidate</th>
    <% min_bar = 0 %>
    <% if(rounds.length - 3 >= 0) %>
      <% min_bar = rounds.length - 3 %>
    <% end %>
    <% rounds[min_bar, rounds.length].each do |round| %>
      <th scope="col" align="center"><%= "ROUND ##{round.round_number}" %></th>
    <% end %>
    <th scope="col">Total Votes</th>
  </tr>
  </thead>
  <tbody>
  <% Candidate.where(["constituency = :u", {u: @parliamentary_constituency.id}]).each do |candidate| %>
    <% party = PoliticalParty.where(["id = :u", {u: candidate.political_party}]).first %>
    <tr>
      <td align="center"><%= candidate.serial_number %></td>
      <td align="center">
        <img src=<%= party.party_symbol %> height="48" width="48"><br>
        <%= party.party_name %>
      </td>
      <td align="center">
        <img src=<%= candidate.photograph %> height="48" width="48"><br>
        <%= candidate.candidate_name %>
      </td>
      <% rounds[min_bar, rounds.length].each do |round| %>
        <% candidate_round = CandidateRound.where(["round_number = :u and candidate = :v", {u: round.id, v: candidate.id}]).first %>
        <td align="center"><%= candidate_round.total_votes %></td>
      <% end %>
      <td align="center"><strong><%= candidate.total_votes %></strong></td>
    </tr>
  <% end %>
  <tr>
    <td></td>
    <td></td>
    <td>
      <% rounds[min_bar, rounds.length].each do |round| %>
      <td align="center">
        <div class="btn-group" role="group" aria-label="Basic example">
          <%= link_to 'Show', round, class: "btn btn-info" %>
          <% if user_signed_in? and current_user.has_role? :admin %>
            <%= link_to 'Destroy', round, method: :delete, data: {confirm: 'Are you sure?'}, class: "btn btn-danger" %>
          <% end %>
        </div>
      </td>
    <% end %>
    </td>
    <td></td>
    <td></td>
  </tr>
  </tbody>
</table>