config/routes.rb
Rails.application.routes.draw do
  get 'users/index'
  get 'users/approve_user'
  get 'users/destroy'
  devise_for :users
  resources :candidate_rounds
  resources :rounds
  resources :candidates
  resources :political_parties
  resources :parliamentary_constituencies
  resources :states
  root to: "states#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/round.rb
class Round < ApplicationRecord
end

app/controllers/rounds_controller.rb
class RoundsController < ApplicationController
  before_action :set_round, only: [:show, :edit, :update, :destroy]

  # GET /rounds
  # GET /rounds.json
  def index
    @rounds = Round.all
  end

  # GET /rounds/1
  # GET /rounds/1.json
  def show
  end

  # GET /rounds/new
  def new
    @constituency = ParliamentaryConstituency.find(params[:constituency])
    @rounds = Round.where(["constituency = :u", { u: @constituency.id }]).length + 1
    @round = Round.new
    @round.round_number = @rounds
    @round.constituency = @constituency.id
    @round.total_votes = 0
    @candidates = Candidate.where(["constituency = :u", { u: @constituency.id }])
  end

  # GET /rounds/1/edit
  def edit
  end

  # POST /rounds
  # POST /rounds.json
  def create
    @round = Round.new(round_params)
    respond_to do |format|
      if @round.save
        @candidates = Candidate.where(["constituency = :u", { u: round_params[:constituency] }])
        @candidates.each do |candidate|
          candidate_round = CandidateRound.new
          candidate_round.candidate = candidate.id
          candidate_round.round_number = @round.id
          candidate_round.total_votes = 0
          candidate_round.save
        end
        format.html { redirect_to @round, notice: 'Round was successfully created.' }
        format.json { render :show, status: :created, location: @round }
      else
        format.html { render :new }
        format.json { render json: @round.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rounds/1
  # PATCH/PUT /rounds/1.json
  def update
    respond_to do |format|
      if @round.update(round_params)
        format.html { redirect_to @round, notice: 'Round was successfully updated.' }
        format.json { render :show, status: :ok, location: @round }
      else
        format.html { render :edit }
        format.json { render json: @round.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rounds/1
  # DELETE /rounds/1.json
  def destroy
    constituency = ParliamentaryConstituency.find(@round.constituency)
    candidate_rounds = CandidateRound.where(["round_number = :u", { u: @round.id }])
    candidate_rounds.each do |round|
      candidate = Candidate.find(round.candidate)
      candidate.total_votes -= round.total_votes
      if(candidate.total_votes < 0)
        candidate.total_votes = 0
      end
      candidate.save
      round.destroy
    end
    @round.destroy
    respond_to do |format|
      format.html { redirect_to constituency, notice: 'Round was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_round
      @round = Round.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def round_params
      params.require(:round).permit(:round_number, :total_votes, :constituency)
    end
end

app/helpers/rounds_helper.rb
module RoundsHelper
end

app/views/rounds/_form.html.erb
<%= form_with(model: round, local: true) do |form| %>
  <% if round.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(round.errors.count, "error") %> prohibited this round from being saved:</h2>

      <ul>
      <% round.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <div class="field">
      <%= form.hidden_field :constituency, value: @constituency.id %>
      <strong><label><%= form.label :constituency %></label></strong>
      <label><%= form.label @constituency.pc_name %><br/></label>
    </div>
  </div>
  <div class="form-group">
    <div class="field">
      <%= form.hidden_field :round_number, value: @rounds %>
      <strong><label><%= form.label :round_number %></label></strong>
      <label><%= form.label @rounds %><br/></label>
    </div>
  </div>
  <div class="form-group">
    <div class="field">
      <strong><label><%= form.label :total_votes %></label></strong>
      <label><%= form.label @round.total_votes %></label>
    </div>
  </div>

  <table class="table">
    <thead>
    <tr align="center">
      <th>Serial Number</th>
      <th>Political Party</th>
      <th>Party Symbol</th>
      <th>Candidate Name</th>
    </tr>
    </thead>

    <tbody>
    <% @candidates.each do |candidate| %>
      <% party = PoliticalParty.where(["id = :u", { u: candidate.political_party }]).first %>
      <tr>
        <td align="center"><%= candidate.serial_number %></td>
        <td align="center"><img src=<%= party.party_symbol %> height="48" width="48"></td>
        <td align="center"><%= party.party_code %></td>
        <td><%= candidate.candidate_name %></td>
      </tr>
    <% end %>
    </tbody>
  </table>

  <div class="actions">
    <%= form.submit "Save Round", class: "btn btn-primary"  %>
  </div>
<% end %>

app/views/rounds/edit.html.erb
<h1>Editing Round</h1>

<%= render 'form', round: @round %>

<%= link_to 'Show', @round %> |
<%= link_to 'Back', rounds_path %>

app/views/rounds/index.html.erb
<h1>Rounds</h1>

<table>
  <thead>
    <tr>
      <th>Round number</th>
      <th>Total votes</th>
      <th>Constituency</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rounds.each do |round| %>
      <tr>
        <td><%= round.round_number %></td>
        <td><%= round.total_votes %></td>
        <td><%= round.constituency %></td>
        <td><%= link_to 'Show', round %></td>
        <td><%= link_to 'Edit', edit_round_path(round) %></td>
        <td><%= link_to 'Destroy', round, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Round', new_round_path %>

app/views/rounds/new.html.erb
<% constituency = ParliamentaryConstituency.where(["id = :u", { u: @round.constituency }]).first %>
<%= link_to 'Back to Constituency', constituency, class: "btn btn-secondary" %>
<br>
<hr>
<br>
<h1>New Round</h1>
<br>
<%= render 'form', round: @round %>

app/views/rounds/show.html.erb
<% constituency = ParliamentaryConstituency.where(["id = :u", {u: @round.constituency }]).first %>
<%= link_to 'Back to Constituency', constituency, class: "btn btn-secondary" %>
<br>
<hr>
<br>
<h3><strong><%= "Parliamentary Constituency #{constituency.pc_code} - #{constituency.pc_name}" %></strong></h3>
<br>
<p>
  <strong>Round Number:</strong>
  <%= @round.round_number %>
</p>

<p>
  <strong>Total Votes:</strong>
  <%= @round.total_votes %>
</p>

<table class="table">
  <thead>
  <tr align="center">
    <th scope="col">Serial number</th>
    <th scope="col">Political Party</th>
    <th scope="col">Candidate</th>
    <th scope="col">Total votes</th>
    <% if user_signed_in? and (current_user.has_role? :approved or current_user.has_role? :admin) %>
      <th colspan="1"></th>
    <% end %>
  </tr>
  </thead>
  <tbody>
  <% CandidateRound.where(["round_number = :u", { u: @round.id}]).each do |round| %>
    <% candidate = Candidate.where(["id = :u", { u: round.candidate}]).first %>
    <% party = PoliticalParty.where(["id = :u", { u: candidate.political_party}]).first %>
    <tr>
      <td align="center"><%= candidate.serial_number %></td>
      <td align="center">
        <img src=<%= party.party_symbol %> height="48" width="48"><br>
        <%= party.party_code %>
      </td>
      <td align="center">
        <img src=<%= candidate.photograph %> height="48" width="48"><br>
        <%= candidate.candidate_name %>
      </td>
      <td align="center"><%= round.total_votes %></td>
      <% if user_signed_in? and (current_user.has_role? :approved or current_user.has_role? :admin) %>
        <td>
          <%= link_to 'Edit', edit_candidate_round_path(round), class: "btn btn-warning"  %>
        </td>
      <% end %>
    </tr>
  <% end %>
  </tbody>
</table>