config/routes.rb
Rails.application.routes.draw do
  get 'users/index'
  get 'users/approve_user'
  get 'users/destroy'
  devise_for :users
  resources :candidate_rounds
  resources :rounds
  resources :candidates
  resources :political_parties
  resources :parliamentary_constituencies
  resources :states
  root to: "states#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ElectionResults</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <% if notice != nil %>
    <div class="alert alert-success" role="alert">
      <%= notice %>
    </div>
  <% end %>

  <% if alert != nil %>
    <div class="alert alert-danger" role="alert">
      <%= alert %>
    </div>
  <% end %>

  <nav class="navbar navbar-expand-lg navbar-light">
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
        <li class="nav-item">
          <%= link_to 'Back', :back, class: "btn btn-secondary mr-1" %>
        </li>
          <%= link_to 'HOME', states_path, class: "btn btn-primary mr-1" %>
        </li>
        <li class="nav-item">
          <%= link_to 'POLITICAL PARTIES', political_parties_path, class: "btn btn-primary mr-1" %>
        </li>
        <% if user_signed_in? and current_user.has_role? :admin %>
          <li class="nav-item"><%= link_to "NEW POLITICAL PARTY", new_political_party_path, class: "btn btn-primary mr-1"%></li>
          <li class="nav-item"><%= link_to "USERS", users_index_url, class: "btn btn-primary mr-1"%></li>
        <% end %>
      </ul>
      <% if user_signed_in? %>
        <%= link_to 'Logout', destroy_user_session_path, class: "btn btn-warning mr-1", method: :delete %>
      <% else %>
        <%= link_to 'Login', new_user_session_url, class: "btn btn-primary mr-1"  %>
        <%= link_to 'New User', new_user_registration_path, class: "btn btn-success mr-1"  %>
      <% end %>
    </div>
  </nav>
  <img src="https://upload.wikimedia.org/wikipedia/en/2/20/Loksabha_Election_2019_ECI_official_logo_Desh_Ka_Mahatyauhar.jpg" class="rounded float-right" alt="logo" height="220" width="220">
  <br>
  <hr>
  <br>
<%= yield %>
</body>
</html>